### ISSUE TITLE
Failed to find the applicable route

### ISSUE THREAD

**Issue by morgonf** [Bondifuzz/shelob#1]
При попытке запустить тестирование сервера https://github.com/microsoft/restler-fuzzer/tree/main/demo_server, фаззер аварийно завершает работу:
![изображение](https://github.com/Bondifuzz/shelob/assets/96179229/ab800bb7-90f5-4434-a657-00ea5e8348ff)

**Comment by morgonf** [comment]
go run main.go -spec=/home/user/restler-fuzzer/demo_server/swagger.json -url=http://localhost:8888/docs

**Comment by elnxl** [comment]
> go run main.go -spec=/home/user/restler-fuzzer/demo_server/swagger.json -url=http://localhost:8888/docs

пофиксил + нужно запускать без `/docs`

```
go run main.go --url http://localhost:8888/ --spec /home/user/restler-fuzzer/demo_server/swagger.json
```
![image](https://github.com/Bondifuzz/shelob/assets/49045314/325be986-57f9-40b6-ba6d-3dc4a088fcbb)

**Comment by morgonf** [comment]
Обновил репу, но ошибка осталась

**Comment by elnxl** [comment]
> Обновил репу, но ошибка осталась

запускаете так?
```
go run main.go --url http://localhost:8888/ --spec /home/user/restler-fuzzer/demo_server/swagger.json
```

**Comment by morgonf** [comment]
Да, действую по инструкции
![изображение](https://github.com/Bondifuzz/shelob/assets/96179229/37b8b880-ea07-4f93-8c19-4ac8dd117b75)
